services:
    api:
        build: ./
        volumes:
            - .:/home/node/app
        networks:
            - node-network
        ports:
            - 3000:3000
        working_dir: /home/node/app

    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        networks:
            - node-network

networks:
    node-network:
